// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/java/tk/skuro/idea/orgmode/parser/Org.flex

package tk.skuro.idea.orgmode.parser;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static tk.skuro.idea.orgmode.parser.OrgTokenTypes.*;

// TODO: see if could reuse org lexer src/org_lexer.l


class _OrgLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int BLOCK = 2;
  public static final int PROPERTIES = 4;
  public static final int TABLE = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  1,  2,  3,  4,  4,  5, 5
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\2\0\1\7\6\0\1\10\1\11\16\0\1\12\7\0"+
    "\1\13\1\0\1\14\1\15\1\0\1\16\1\0\1\17"+
    "\4\0\1\20\1\21\1\22\1\0\1\23\1\24\1\25"+
    "\12\0\1\26\34\0\1\27\1\0\1\30\6\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\2\2\1\3\4\1\1\2\1\3\1\4"+
    "\1\1\1\5\4\6\6\7\7\10\1\11\2\0\2\3"+
    "\3\0\1\12\3\0\1\3\1\13\1\0\2\5\1\6"+
    "\1\2\2\0\1\3\1\0\1\2\2\11\1\0\2\3"+
    "\1\14\1\0\1\15\1\0\1\3\1\0\2\3\2\0"+
    "\1\6\4\0\2\3\3\0\1\16\2\3\1\0\1\17"+
    "\1\6\3\0\2\3\1\20\2\0\2\16\2\3\1\0"+
    "\2\17\1\6\1\21\2\0\2\3\2\0\2\3\1\0"+
    "\1\6\2\0\1\3\1\20\2\0\1\3\1\20\1\0"+
    "\1\22\1\0\1\3\1\0\1\3\2\0\1\23\1\0"+
    "\1\23\3\0\1\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\31\0\62\0\113\0\144\0\175\0\226\0\257"+
    "\0\310\0\341\0\372\0\u0113\0\u012c\0\u0145\0\u015e\0\u0177"+
    "\0\u0190\0\u01a9\0\u01c2\0\u01db\0\62\0\113\0\u01f4\0\226"+
    "\0\u020d\0\u0226\0\372\0\u023f\0\u012c\0\226\0\u0258\0\310"+
    "\0\u0226\0\372\0\u0113\0\u012c\0\u0271\0\u028a\0\u0113\0\u02a3"+
    "\0\u02bc\0\u02d5\0\u02ee\0\u012c\0\u012c\0\u0307\0\u0320\0\u01a9"+
    "\0\u0339\0\u0352\0\u036b\0\u0384\0\u039d\0\u03b6\0\u020d\0\u03cf"+
    "\0\u023f\0\u03e8\0\u0401\0\u0258\0\226\0\u041a\0\u0433\0\u044c"+
    "\0\u0465\0\u02d5\0\u047e\0\226\0\u0497\0\u04b0\0\u04c9\0\u04e2"+
    "\0\u04fb\0\u0514\0\u052d\0\u0546\0\u055f\0\u0578\0\u0591\0\u05aa"+
    "\0\u05c3\0\u05dc\0\u05f5\0\u060e\0\u0627\0\u0640\0\u0659\0\u0672"+
    "\0\u068b\0\u06a4\0\u06bd\0\u06d6\0\u06ef\0\u0708\0\u0721\0\u073a"+
    "\0\226\0\u0753\0\u076c\0\226\0\u0785\0\u079e\0\u07b7\0\u07d0"+
    "\0\226\0\u07e9\0\u0802\0\226\0\u081b\0\u0834\0\u084d\0\u0866"+
    "\0\u087f\0\u0898\0\u08b1\0\u08ca\0\u08e3\0\u08fc\0\u0915\0\u0866"+
    "\0\u092e\0\u0866\0\u0947\0\u08ca\0\u0960\0\u08ca\0\u0979\0\u08fc"+
    "\0\u0992\0\u09ab\0\u09c4\0\u09dd\0\u09f6\0\u09ab\0\u09ab\0\u09dd"+
    "\0\u09dd\0\u0a0f\0\u0a28\0\u0a41\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\11\1\0\2\11\1\10\1\12\1\13"+
    "\1\7\1\14\13\7\1\15\1\7\1\16\1\7\1\17"+
    "\1\11\1\0\2\11\1\17\1\20\1\21\1\7\1\22"+
    "\13\7\1\15\1\23\1\16\1\24\1\25\1\11\1\24"+
    "\1\25\1\11\1\25\23\24\1\26\1\11\1\24\1\25"+
    "\1\11\1\26\1\27\21\24\1\30\1\31\1\11\1\0"+
    "\2\11\1\31\1\32\1\33\1\30\1\34\13\30\1\35"+
    "\2\30\1\36\1\37\1\40\1\36\2\40\1\37\1\41"+
    "\1\42\1\36\1\43\13\36\1\44\1\45\1\36\32\0"+
    "\1\10\1\11\1\0\2\11\1\10\1\46\2\0\1\47"+
    "\17\0\2\11\1\0\3\11\22\0\2\50\4\0\3\50"+
    "\1\51\17\50\2\52\1\0\2\52\1\0\23\52\15\0"+
    "\1\53\13\0\2\54\1\0\2\54\1\0\20\54\1\55"+
    "\2\54\2\56\1\0\2\56\1\0\22\56\2\0\1\17"+
    "\1\11\1\0\2\11\1\17\1\57\2\0\1\60\16\0"+
    "\2\50\4\0\3\50\1\61\17\50\2\21\1\0\1\21"+
    "\1\52\1\0\23\21\6\0\1\62\6\0\1\53\4\0"+
    "\1\63\6\0\2\23\1\64\1\23\1\0\1\65\23\23"+
    "\2\24\1\0\2\24\1\0\25\24\1\0\2\24\1\0"+
    "\3\24\1\66\17\24\1\0\1\67\1\11\1\0\2\11"+
    "\1\67\1\70\2\0\1\71\16\0\2\50\4\0\3\50"+
    "\1\72\17\50\15\0\1\73\14\0\1\74\1\11\1\0"+
    "\2\11\1\74\1\70\2\0\1\47\16\0\2\45\1\75"+
    "\1\45\1\0\1\76\23\45\11\0\1\77\17\0\2\50"+
    "\4\0\25\50\4\0\5\50\1\100\1\50\1\101\13\50"+
    "\2\52\1\0\2\52\1\0\2\52\1\102\20\52\20\0"+
    "\1\103\10\0\2\56\1\0\2\56\1\0\22\56\1\104"+
    "\11\0\1\105\17\0\2\106\1\0\1\107\2\0\5\106"+
    "\1\110\1\106\1\111\13\106\2\62\1\0\1\62\2\0"+
    "\23\62\23\0\1\112\34\0\1\113\3\0\1\64\24\0"+
    "\1\113\1\0\2\24\1\0\2\24\1\0\7\24\1\114"+
    "\13\24\11\0\1\115\17\0\2\50\4\0\7\50\1\101"+
    "\13\50\20\0\1\116\12\0\1\75\41\0\1\117\1\0"+
    "\1\120\13\0\2\50\4\0\7\50\1\121\15\50\4\0"+
    "\12\50\1\122\10\50\14\0\1\123\14\0\2\107\1\0"+
    "\1\107\2\0\5\107\1\124\1\107\1\125\13\107\2\106"+
    "\1\0\1\107\2\0\4\106\1\126\16\106\2\107\1\0"+
    "\1\107\2\0\4\107\1\126\16\107\2\106\1\0\1\107"+
    "\2\0\4\106\1\126\2\106\1\127\15\106\1\0\1\107"+
    "\2\0\4\106\1\126\5\106\1\130\10\106\21\0\1\131"+
    "\17\0\1\132\20\0\2\24\1\0\2\24\1\0\12\24"+
    "\1\133\10\24\15\0\1\120\27\0\1\134\31\0\1\135"+
    "\33\0\1\136\10\0\2\50\4\0\10\50\1\137\14\50"+
    "\4\0\6\50\1\140\14\50\12\0\1\141\16\0\2\107"+
    "\1\0\1\107\2\0\4\107\1\126\2\107\1\142\15\107"+
    "\1\0\1\107\2\0\4\107\1\126\5\107\1\143\10\107"+
    "\2\126\1\144\1\126\1\0\1\145\23\126\2\106\1\0"+
    "\1\107\2\0\4\106\1\126\3\106\1\146\14\106\1\0"+
    "\1\107\2\0\4\106\1\126\1\106\1\147\14\106\22\0"+
    "\1\150\10\0\1\151\2\0\1\152\2\0\1\132\16\0"+
    "\1\132\1\0\2\24\1\0\2\24\1\0\6\24\1\153"+
    "\14\24\12\0\1\154\34\0\1\155\26\0\1\156\14\0"+
    "\2\50\4\0\11\50\1\157\13\50\4\0\20\50\1\160"+
    "\2\50\2\107\1\0\1\107\2\0\4\107\1\126\3\107"+
    "\1\161\14\107\1\0\1\107\2\0\4\107\1\126\1\107"+
    "\1\162\14\107\2\0\1\144\26\0\2\106\1\0\1\107"+
    "\2\0\4\106\1\126\4\106\1\163\13\106\1\0\1\107"+
    "\2\0\4\106\1\126\13\106\1\164\2\106\15\0\1\165"+
    "\15\0\1\151\26\0\2\24\1\0\2\24\1\0\20\24"+
    "\1\166\2\24\17\0\1\167\37\0\1\170\2\0\2\50"+
    "\4\0\12\50\1\171\10\50\2\172\1\0\1\172\2\0"+
    "\23\172\2\107\1\0\1\107\2\0\4\107\1\126\4\107"+
    "\1\173\13\107\1\0\1\107\2\0\4\107\1\126\13\107"+
    "\1\174\2\107\2\106\1\0\1\107\2\0\4\106\1\126"+
    "\5\106\1\175\10\106\2\176\1\0\1\176\2\0\4\176"+
    "\1\126\16\176\23\0\1\177\5\0\2\200\1\0\1\200"+
    "\1\24\1\0\23\200\20\0\1\201\10\0\2\50\4\0"+
    "\20\50\1\202\2\50\2\107\1\0\1\107\2\0\4\107"+
    "\1\126\5\107\1\203\10\107\2\106\1\0\1\107\2\0"+
    "\4\106\1\126\13\106\1\204\2\106\25\0\1\205\31\0"+
    "\1\206\2\0\2\207\1\0\1\207\2\0\23\207\2\107"+
    "\1\0\1\107\2\0\4\107\1\126\13\107\1\210\2\107"+
    "\2\211\1\0\1\211\2\0\4\211\1\126\16\211\17\0"+
    "\1\212\26\0\1\213\37\0\1\214\16\0\1\215\16\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2650];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\20\1\1\11\5\1\1\11\7\1\2\0"+
    "\2\1\3\0\1\1\3\0\2\1\1\0\4\1\2\0"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\3\1\1\0"+
    "\1\11\1\0\1\1\1\0\2\1\2\0\1\1\4\0"+
    "\2\1\3\0\3\1\1\0\2\1\3\0\2\1\1\11"+
    "\2\0\1\11\3\1\1\0\1\11\2\1\1\11\2\0"+
    "\2\1\2\0\2\1\1\0\1\1\2\0\2\1\2\0"+
    "\2\1\1\0\1\1\1\0\1\1\1\0\1\1\2\0"+
    "\1\1\1\0\1\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _OrgLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL.charAt(zzMarkedPosL-1)) {
        case '\n':
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':  // fall through
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL.charAt(zzMarkedPosL) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL.charAt(zzMarkedPosL) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TEXT;
            }
          // fall through
          case 21: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 22: break;
          case 3:
            { return COMMENT;
            }
          // fall through
          case 23: break;
          case 4:
            { yybegin(YYINITIAL); return OUTLINE;
            }
          // fall through
          case 24: break;
          case 5:
            { yybegin(TABLE); return TABLE_ROW;
            }
          // fall through
          case 25: break;
          case 6:
            { return BLOCK_CONTENT;
            }
          // fall through
          case 26: break;
          case 7:
            { return DRAWER_CONTENT;
            }
          // fall through
          case 27: break;
          case 8:
            { yybegin(YYINITIAL); yypushback(1); break;
            }
          // fall through
          case 28: break;
          case 9:
            { return TABLE_ROW;
            }
          // fall through
          case 29: break;
          case 10:
            { return UNDERLINE;
            }
          // fall through
          case 30: break;
          case 11:
            { yybegin(YYINITIAL); return CODE;
            }
          // fall through
          case 31: break;
          case 12:
            { return BOLD;
            }
          // fall through
          case 32: break;
          case 13:
            { return VERBATIM;
            }
          // fall through
          case 33: break;
          case 14:
            { yybegin(YYINITIAL); return KEYWORD;
            }
          // fall through
          case 34: break;
          case 15:
            { yybegin(TABLE); return TABLE_HEADER;
            }
          // fall through
          case 35: break;
          case 16:
            { return UNMATCHED_DELIMITER;
            }
          // fall through
          case 36: break;
          case 17:
            { yybegin(YYINITIAL); return DRAWER_DELIMITER;
            }
          // fall through
          case 37: break;
          case 18:
            { yybegin(YYINITIAL); return BLOCK_END;
            }
          // fall through
          case 38: break;
          case 19:
            { yybegin(BLOCK); return BLOCK_START;
            }
          // fall through
          case 39: break;
          case 20:
            { yybegin(PROPERTIES); return DRAWER_DELIMITER;
            }
          // fall through
          case 40: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
